ktor:
  application:
    modules:
      - pl.dev.bkwiatkowski.ApplicationKt.module
  deployment:
    host: "0.0.0.0"
    port: 8080
cors:
  hosts:
    - ${CORS_HOSTS}
jwt:
  domain: ${JWT_ISSUER}
  audience: "jwt-audience"
  realm: "orienteeringApp"
  secret: ${JWT_SECRET}
  expiresInMinutes: 6
  refreshExpiresInDays: 30
postgres:
  host: ${DB_HOST}
  port: "5432"
  database: ${POSTGRES_DB}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
images:
  storageDir: ${IMAGES_STORAGE_DIR}
