ktor:
  application:
    modules:
      - pl.dev.bkwiatkowski.ApplicationKt.module
  deployment:
    host: "0.0.0.0"
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor orienteering app"
  secret: ${JWT_SECRET}
postgres:
  host: ${DB_HOST}
  port: "5432"
  database: ${POSTGRES_DB}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
